【22:40:49】      message = 获取UserInfo , exception = 
【22:40:53】      message = 签到 , exception = 
【22:40:53】      message = 查询新邮件 , exception = 
【22:41:16】      message = 终止作战 , exception = 
【22:46:07】      message = 获取UserInfo , exception = 
【22:46:11】      message = 签到 , exception = 
【22:46:11】      message = 查询新邮件 , exception = 
【22:48:12】      message = 获取UserInfo , exception = 
【22:48:16】      message = 签到 , exception = 
【22:48:16】      message = 查询新邮件 , exception = 
【22:49:03】      message = 归雪 无法部署梯队，请登陆游戏检查 , exception = error:2
【22:55:11】      message = 获取UserInfo , exception = 
【22:55:15】      message = 签到 , exception = 
【22:55:15】      message = 查询新邮件 , exception = 
【22:55:16】      message = 终止作战 , exception = 
【23:03:48】      message = 获取UserInfo , exception = 
【23:03:52】      message = 签到 , exception = 
【23:03:52】      message = 查询新邮件 , exception = 
【23:03:58】      message = 终止作战 , exception = 
【23:05:55】      message = endTurn Error , exception = error:2
【23:06:01】      message = Simulation_battleFinish Error , exception = error:2
【23:06:05】      message = startTurn Error , exception = error:2
【23:06:14】      message = teamMove Error , exception = error:203|行动点数计算有误
【23:14:12】      message = 获取UserInfo , exception = 
【23:14:16】      message = 签到 , exception = 
【23:14:16】      message = 查询新邮件 , exception = 
【23:14:17】      message = 终止作战 , exception = 
【23:15:46】      message = endTurn Error , exception = error:2
【23:15:51】      message = Simulation_battleFinish Error , exception = error:2
【23:15:55】      message = startTurn Error , exception = error:2
【23:16:00】      message = teamMove Error , exception = error:203|行动点数计算有误
【23:31:31】      message = 获取UserInfo , exception = 
【23:31:35】      message = 签到 , exception = 
【23:31:35】      message = 查询新邮件 , exception = 
【23:31:36】      message = 终止作战 , exception = 
【23:34:16】      message = 获取UserInfo , exception = 
【23:34:20】      message = 签到 , exception = 
【23:34:20】      message = 查询新邮件 , exception = 
【23:34:21】      message = 终止作战 , exception = 
【23:34:34】      message = 获取UserInfo , exception = 
【23:34:38】      message = 签到 , exception = 
【23:34:38】      message = 查询新邮件 , exception = 
【00:35:31】      message = 获取UserInfo , exception = 
【00:35:36】      message = 签到 , exception = 
【00:35:36】      message = 查询新邮件 , exception = 
【00:35:36】      message = 终止作战 , exception = 
【00:37:02】      message = 获取UserInfo , exception = 
【00:37:06】      message = 签到 , exception = 
【00:37:06】      message = 查询新邮件 , exception = 
【00:37:07】      message = 终止作战 , exception = 
【00:43:01】      message = 获取UserInfo , exception = 
【00:43:05】      message = 签到 , exception = 
【00:43:05】      message = 查询新邮件 , exception = 
【00:43:06】      message = 终止作战 , exception = 
【00:44:28】      message = 获取UserInfo , exception = 
【00:44:36】      message = 签到 , exception = 
【00:44:36】      message = 查询新邮件 , exception = 
【00:44:36】      message = 终止作战 , exception = 
【00:49:34】      message = 获取UserInfo , exception = 
【00:49:38】      message = 签到 , exception = 
【00:49:38】      message = 查询新邮件 , exception = 
【00:49:39】      message = 终止作战 , exception = 
【01:09:07】      message = 人形 : 6746852 扩编 
【01:27:11】      message = 获取新人形 : evo 3 ,意不意外 惊不惊喜 
【01:32:39】      message = 获取新人形 : ots-44 ,意不意外 惊不惊喜 
【01:42:33】      message = 获取新人形 : 59式 ,意不意外 惊不惊喜 
【01:45:07】      message = 获取新人形 : g28 ,意不意外 惊不惊喜 
【01:53:46】      message = 数字天空登陆 , exception = 
【01:53:47】      message = 获取时间信息 , exception = 
【01:53:48】      message = 获取Sign , exception = 
【01:53:49】      message = 获取UserInfo , exception = 
【01:53:55】      message = 签到 , exception = 
【01:53:55】      message = 查询新邮件 , exception = 
【01:54:03】      message = 终止作战 , exception = 
【01:58:04】      message = 数字天空登陆 , exception = 
【01:58:05】      message = 获取时间信息 , exception = 
【01:58:06】      message = 获取Sign , exception = 
【01:58:07】      message = 获取UserInfo , exception = 
【01:58:11】      message = 签到 , exception = 
【01:58:11】      message = 查询新邮件 , exception = 
【02:10:02】      message = 收集数据 数据监测枢纽  
【02:10:03】      message =  获取数据样本出错 , exception = error:0
【02:13:00】      message = 数字天空登陆 , exception = 
【02:13:01】      message = 获取时间信息 , exception = 
【02:13:02】      message = 获取Sign , exception = 
【02:13:03】      message = 获取UserInfo , exception = 
【02:13:07】      message = 签到 , exception = 
【02:13:07】      message = 查询新邮件 , exception = 
【02:13:40】      message = 终止作战 , exception = 
【02:15:37】      message = 数字天空登陆 , exception = 
【02:15:37】      message = 获取时间信息 , exception = 
【02:15:38】      message = 获取Sign , exception = 
【02:15:40】      message = 获取UserInfo , exception = 
【02:15:44】      message = 签到 , exception = 
【02:15:44】      message = 查询新邮件 , exception = 
【02:15:54】      message = 终止作战 , exception = 
【02:35:02】      message = 数字天空登陆 , exception = 
【02:35:05】      message = LoginDigitalSKY , exception = false System.Net.WebException: 由于目标计算机积极拒绝，无法连接。 由于目标计算机积极拒绝，无法连接。 ---> System.Net.Http.HttpRequestException: 由于目标计算机积极拒绝，无法连接。 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.HttpWebRequest.SendRequest()
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at System.Net.WebClient.GetWebResponse(WebRequest request)
   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)
   at System.Net.WebClient.UploadBits(WebRequest request, Stream readStream, Byte[] buffer, Int32 chunkSize, Byte[] header, Byte[] footer)
   at System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   at System.Net.WebClient.UploadData(Uri address, String method, Byte[] data)
   at System.Net.WebClient.UploadData(String address, String method, Byte[] data)
   at GFHelp.Core.API.BaseRequset.DoPost(String url, Byte[] postData) in C:\Users\jack\Desktop\CS\GFHelp-Web\GFHelp.Core\API\BaseRequset.cs:line 40
【23:45:38】      message = 程序已注销 请重新创建实例 
